name: build and test
on: push
jobs:
  build_and_test:
    strategy:
      matrix:
        java-version: [17, 21]
        os: [ubuntu-24.04, windows-2025, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'zulu'
      - run: mvnw verify
